<?php

/**
 * @file
 * This file serves as a stub file for the many Examples modules in the
 * @link http://drupal.org/project/examples Examples for Developers Project @endlink
 * which you can download and experiment with.
 *
 * One might say that examples.module is an example of documentation. However,
 * note that the example submodules define many doxygen groups, which may or
 * may not be a good strategy for other modules.
 */

/**
 * @defgroup examples Examples
 * @{
 * 针对Drupal核心功能的，具有完善文档的示例。
 *
 * 开发者能够通过试验模块的方式，能够快速的学习使用Drupal某一方面API。
 *
 * 从下面网址下载本模块（当然，还可以参与提交bug报告、补丁和文档）
 *
 * http://drupal.org/project/examples
 */

/**
 * Implements hook_help().
 * @param string $path  IDE语法检查强迫症
 * @param array $arg  IDE语法检查强迫症
 */
function examples_help($path, $arg) {
  // 回复: http://drupal.org/node/767204
  // 5. 我们需要一个主要组（Examples），存在于examples.module内。
  // 这个examples.module应该主要是一些格式化的文档，指向其他模块。
  // 他还有一个hook_help()，来解释这一模块的目标以及如何访问其他例子。


}

/**
 * @} End of 'defgroup examples'.
 */
