<?php

/**
 * @file
 * Implements simpletest_example_test module.
 */

/**
 * SimpleTest示例的Mock模块
 *
 * 我们可以启用这个模块并利用它测试simpletest_module。
 *
 * @ingroup simpletest_example
 */

/**
 * Implements hook_node_view().
 *
 * 这里将会为指定类型的Node添加一些内容。
 *
 * @ingroup simpletest_example
 */
function simpletest_example_test_node_view($node, $view_mode, $langcode) {
  if ($node->type == 'simpletest_example') {
    $node->content['simpletest_example_test_section'] = array(
      '#markup' => t('The test module did its thing.'),
      '#weight' => -99,
    );
  }
}
