<?php
/**
 * @file render_example.install
 * Install/uninstall routines for render example.
 */

/**
 * Implementation of hook_uninstall().
 */
function render_example_uninstall() {
  variable_del('render_example_show_page');
  variable_del('render_example_show_block');
  variable_del('render_example_reverse_sidebar');
  variable_del('render_example_note_about_render_arrays');
  variable_del('render_example_move_navigation_menu');
}
